using System;
using System.Collections.Generic;
using System.Numerics;
using System.Text;
using BepInEx.Configuration;
using UnityEngine;

namespace ErenshorREL
{
    public class Utilities
    {
        internal static void ApplyConfig()
        {

            ErenshorREL._configApplied = true;
        }

        internal static void GenerateConfigs()
        {
            ErenshorREL.RandomLootToggle = ErenshorREL.context.config("1 - RandomLoot", "Enable RandomLoot", ErenshorREL.Toggle.On, "This file is automatically generated by the Erenshor Random Epic Loot Mod plugin and is used to configure various mod features. You can revert to the defaults if you experience issues.\nEnable additional Random Loot?");
            ErenshorREL.RandomLootLevelsBelow = ErenshorREL.context.config("1 - RandomLoot", "Number of item levels below", 5, "The number of item levels to choose items from below the target NPC's level. Acceptable Range <int> 0-50");
            ErenshorREL.RandomLootLevelsAbove = ErenshorREL.context.config("1 - RandomLoot", "Number of item levels above", 1, "The number of item levels to choose items from above the target NPC's level. Acceptable Range <int> 0-50");
            ErenshorREL.RandomLootChance = ErenshorREL.context.config("1 - RandomLoot", "Chance of an additional random loot", 0.1f, "The chance of adding an additional random drop. Acceptable Range <float> 0.0f-1.0f meaning 0.1 is a 10% chance");
        }
    }
}
