using System;
using System.Collections.Generic;
using System.Numerics;
using System.Text;
using BepInEx.Configuration;
using UnityEngine;

namespace ErenshorREL
{
    public class Utilities
    {
        internal static void ApplyConfig()
        {

            ErenshorREL._configApplied = true;
        }

        internal static void GenerateConfigs()
        {
            ErenshorREL.RandomLootToggle = ErenshorREL.context.config("1 - RandomLoot", "Enable RandomLoot", ErenshorREL.Toggle.On, "This file is automatically generated by the Erenshor Random Epic Loot Mod plugin and is used to configure various mod features. You can revert to the defaults if you experience issues.\nEnable additional Random Loot?");
            ErenshorREL.RandomLootLevelsBelow = ErenshorREL.context.config("1 - RandomLoot", "Number of item levels below", 5, "The number of item levels to choose items from below the target NPC's level. Acceptable Range <int> 0-100");
            ErenshorREL.RandomLootLevelsAbove = ErenshorREL.context.config("1 - RandomLoot", "Number of item levels above", 1, "The number of item levels to choose items from above the target NPC's level. Acceptable Range <int> 0-4");
            ErenshorREL.RandomLootRareNPCChance = ErenshorREL.context.config("1 - RandomLoot", "Rare NPCS: Percent chance of a random loot", 50.0f, "The chance of adding an additional random drop. Acceptable Range <float> 0.0f-100.0f meaning 10.0f is 10% chance");
            ErenshorREL.RandomLootCommonNPCChance = ErenshorREL.context.config("1 - RandomLoot", "Common NPCS: Percent chance of a random loot", 3.0f, "The chance of adding an additional random drop. Acceptable Range <float> 0.0f-100.0f meaning 10.0f is 10% chance");
            ErenshorREL.RandomLootText = ErenshorREL.context.config("1 - RandomLoot", "Random Loot Text", "Mysterious forces have added a new treasure: ", "The text displayed when a new random item is added in addition to the item name and NPC name.");
            ErenshorREL.RandomLootDebug = ErenshorREL.context.config("1 - RandomLoot", "Debug Output", ErenshorREL.Toggle.Off, "Display debug messages and output of the random loot functions");
        }
    }
}
